steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.backend', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/asv-repo/asv-backend:latest', '.']
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/asv-repo/asv-backend:latest'
